---
title: "Google Search Trends Over Time: ‘LGBTQ’ and ‘Watermelon’"
author: Willi Zhang
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
```

### 2. Import & Prepare Dataset
```{r}
trends_data <- read.csv( "multiTimeline.csv",
                         skip = 1,
                         check.names = FALSE )

str( trends_data )

long_data <- trends_data %>%
  pivot_longer(
    cols = -Month,
    names_to = "Search_Term",
    values_to = "Search_Interest"
    ) %>%
  mutate(
    Month = as.Date( paste0( Month, "-01" ) ),
    Category = ifelse( grepl( "Watermelon", Search_Term ), "Watermelon", "LGBTQ" )
    )

icon_labels <- c(
  "LGBTQ: (United Kingdom)" = "UK (\U1F308)",
  "LGBTQ: (Sweden)" = "Sweden (\U1F308)",
  "LGBTQ: (United States)" = "US (\U1F308)",
  "Watermelon: (United Kingdom)" = "UK (\U1F349)"
  )

long_data <- long_data %>%
  mutate(
    Icon_Label = recode( Search_Term, !!!icon_labels )
    )

str( long_data )
summary( long_data )
```

### 3. Plotting
```{r}
# interactive plot

p <- plot_ly(
  
  data = long_data,
  x = ~ Month,
  y = ~ Search_Interest,
  color = ~ Icon_Label,
  colors = c(
    "UK (\U1F308)" = "#C77CFF",
    "Sweden (\U1F308)" = "#00BFC4",
    "US (\U1F308)" = "#7CAE00",
    "UK (\U1F349)" = "red" ),
  
  type = 'scatter',
  mode = 'lines',
  line = list( width = 1.5 ) ) %>%
  
  layout(
    title = list(
      text = "Google Search Trends for ‘LGBTQ’ and ‘Watermelon’ Over Time<br><span style='font-size:12px;'>From 2009-01-01 to 2024-12-31</span>",
      font = list( family = "Arial", size = 16 ),
      x = 0.1,  # Align title to the left
      y = 0.95    # Vertical positioning
      ),
    
    xaxis = list(
      title = "Year",
      tickformat = "%Y",
      tickvals = seq( as.Date( "2009-07-01" ), as.Date( "2024-07-01" ), by = "3 year" ),
      range = c( as.Date( "2009-01-01" ) - 150, as.Date( "2024-12-01") + 100 ),
      titlefont = list( family = "Arial", size = 14 ),
      tickfont = list( family = "Arial", size = 14 ),
      linecolor = "black",
      linewidth = 1,
      ticks = "outside",
      showgrid = FALSE
      ),
    
    yaxis = list(
      title = "Search Interest",
      titlefont = list( family = "Arial", size = 14 ),
      tickfont = list( family = "Arial", size = 14 ),
      range = c(-3, 103),
      zeroline = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      range = c(0, 102),
      ticks = "outside",
      mirror = FALSE,
      showgrid = FALSE
      ),
    
    legend = list(
      title = list( text = NULL ),
      font = list( family = "Arial", size = 14 ),
      x = 0.05,
      xanchor = "left",
      y = 0.8,
      yanchor = "top"
      ),
    
    margin = list(
      t = 60,  # Add space at the top for the title (measured in pixels)
      r = 40,  # Right margin
      b = 50,  # Bottom margin
      l = 60   # Left margin
    )
  )

p
```